---
title: "Project Data Collection"
author: "GuanghongFu"
date: "July 25, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(stringr)
library(xml2)
library(rvest)
library(readr)
library(tidyr)
library(plyr)
```

## R Markdown

# 7.25 Get top 100 movies from 1980 to 2015 from www.rottentomatoes.com
```{r}
year <- as.character(1950:2015)

df = data.frame(matrix(vector(), 0, 6,
                dimnames=list(c(), c("Rank", "RatingTomatometer", 
                                     "Title", "No..of.Reviews", "year", "html_suffix"))),
                stringsAsFactors=F)


top100_movies <- for (i in year) {
  html_address <- str_c("https://www.rottentomatoes.com/top/bestofrt/?year=", i)
  
  # Get the table of the ranking
  table <- read_html(html_address) %>%
    html_nodes(xpath = "//table[@class = 'table']") %>%
    html_table(fill = TRUE) %>% 
    data.frame() %>%
    mutate(year = i)
  
  # Get the html suffix for each movie 
  html_suffix <- read_html(html_address) %>%
    html_nodes(xpath = "//table//a") %>%
    html_attr("href") %>%
    data.frame() %>%
    .[1:nrow(table), ]
  
  # Add suffix to the table
  table <- table %>%
    mutate(html_suffix = html_suffix)
    
  # Combine it to df
  df <- rbind(df, table)
}

write_csv(df, "top100_movies.csv")
```

